name: Deployment pipeline
permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: list dir
        run: ls -a
      - name: cd frontend
        run: cd frontend
      - name: lint frontend
        run: npm run lint
      - name: build frontend
        run: npm run build
      - name: move build
        run: mv build ../backend/.
      - name: cd backend
        run: cd ../backend
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: npm run build
        run: npm run build
      - name: deploy to heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: marty-phonebook
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: 'https://marty-pokedex.herokuapp.com/health'
          rollbackonhealthcheckfailed: true
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  notification:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') && success() }}
        with:
          severity: info
          details: Build Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') && failure() }}
        with:
          severity: error
          username: DeploymentStatusChecker
          text: ${{ github.events.commits[0].id }}
          description: Commit ID
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
